# Configuração do Spring Cloud Gateway para o O11y Labs
gateway:
  routes:
    - name: users
      protocol: http
      host: localhost
      port: 3001
      publicPath: /api/users
      realPath: /moock/users
      stripPrefix: 2

    - name: products
      protocol: http
      host: localhost
      port: 3001
      publicPath: /api/books
      realPath: /moock/books
      stripPrefix: 2

# spring:  
#   cloud:
#     gateway:
#       server:
#         webflux:          
#           routes:
#             - id: users # rest
#               uri: http://localhost:3001
#               predicates:
#                 - Path=/api/users # path public que será exposto pelo gateway
#               methods:
#                 - GET
#               filters:
#                 - StripPrefix=2 # Remove /api/users do path antes de encaminhar
#                 - SetPath=/moock/users # Define o novo path

#             - id: products # grpc (proxy interno)
#               uri: http://localhost:8082 # Outra URL fictícia
#               predicates:
#                 - Path=/api/products # path public que será exposto pelo gateway
#               filters:
#                 - StripPrefix=2 # Remove /api/products do path antes de encaminhar

management:
  endpoints:
    web:
      exposure:
        include: "*" # Expõe todos os endpoints do Actuator (incluindo /actuator/prometheus para métricas)
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # 100% de amostragem para traces (para lab, pode ser menor em produção)
  datadog:
    metrics:
      export:
        enabled: true
        step: 30s # Intervalo de envio de métricas para o Datadog

logging:
  level:
    root: INFO
    # br.com.jhegner.o11ylabs: INFO 