# Configuração do Spring Cloud Gateway para o O11y Labs
gateway:
  routes:
    - name: users
      protocol: http
      host: localhost
      port: 3001
      publicPath: /api/users
      realPath: /moock/users
      stripPrefix: 2

    - name: products
      protocol: http
      host: localhost
      port: 3001
      publicPath: /api/books
      realPath: /moock/books
      stripPrefix: 2

management:
  endpoints:
    web:
      exposure:
        include: "*" # Expõe todos os endpoints do Actuator (incluindo /actuator/prometheus para métricas)
  logging:
    export:
      enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # 100% de amostragem para traces (para lab, pode ser menor em produção)
  datadog:
    metrics:
      export:
        enabled: true
        step: 30s # Intervalo de envio de métricas para o Datadog
        api-key: ${DD_API_KEY}
        application-key: ${DD_APPS_KEY}
        uri: https://${DD_URI_SITE}

logging:
  level:
    root: INFO
    # br.com.jhegner.o11ylabs: INFO 