server:
  port: 8080

spring:
  profiles:
    active: dev,prettylog # prettylog for dev
    #active: prod
  main:
      banner-mode: OFF
      web-application-type: REACTIVE
  application:
    name: o11y-labs-app1-gateway

---

spring:  
  cloud:
    gateway:
      server:
        webflux:          
          routes:
            - id: users_route # rest
              uri: ${gateway.routes[0].protocol}://${gateway.routes[0].host}:${gateway.routes[0].port}
              predicates:
                - Path=${gateway.routes[0].publicPath}
              methods:
                - GET
              filters:
                - StripPrefix=${gateway.routes[0].stripPrefix}
                - SetPath=${gateway.routes[0].realPath}

            - id: books_route # grpc (proxy interno)
              uri: ${gateway.routes[1].protocol}://${gateway.routes[1].host}:${gateway.routes[1].port}
              predicates:
                - Path=${gateway.routes[1].publicPath}
              methods:
                - GET
              filters:
                - StripPrefix=${gateway.routes[1].stripPrefix}
                - SetPath=${gateway.routes[1].realPath}